spring:
  application:
    name: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
